### PR TITLE
librewolf update to version 122.0-1.

### PR DESCRIPTION
**Pull request by SpidFightFR**
Hey, hope you're doing great !

A PR for the 122.0-1 release !

As always i'll test before making it public.

have a nice day !

### CODE REVIEW

**Comment by SpidFightFR** [comment]
Okay some patches seem to be outdated, i'll see what i can do later on today.

**Comment by SpidFightFR** [comment]
Alright, it looks like it built just fine on my side, imma test it later on !

**Comment by SpidFightFR** [comment]
image

It's all good !

**Comment by index-0** [comment]
Thanks!

**Pull request merged**
