### PR TITLE
librewolf: update to 127.0.2-2

### PR DESCRIPTION
**Pull request by SpidFightFR**
Hey, here is the pr for 127.0.2-2.

Take care !

### CODE REVIEW

**Comment by SpidFightFR** [comment]
imma try that tomorrow

**Comment by SpidFightFR** [comment]
I edited a little mistake i made yesterday, should be good now !

**Comment by SpidFightFR** [comment]
image
Also the screenshot as usual.

Take care !

**Comment by index-0** [comment]
Thanks

**Pull request merged**
