### PR TITLE
librewolf: update to version 119.0-5.

### PR DESCRIPTION
**Pull request by SpidFightFR**
Hey dude !

A little PR for the latest version of Librewolf.
Nice job, with the python 3.12 thing, btw !

### CODE REVIEW

**Comment by SpidFightFR** [comment]
~~UPDATE: You maybe don't want to update to that version, it brought issues to the toolbar next to the urlbar, extension were hidden, and it's glitchy overall.~~

~~I had to revert to your latest release to make things work again.~~

**Comment by SpidFightFR** [comment]
UPDATE (again): should be fixed, see [here](https://codeberg.org/librewolf/issues/issues/1636) for more info.

**Comment by SpidFightFR** [comment]
image

Can confirm, it is now fixed :)

**Comment by index-0** [comment]
Nice work! Thanks

**Pull request merged**
