### PR TITLE
librewolf: update to 130.0-3.

### PR DESCRIPTION
**Pull request by SpidFightFR**
Hey man ! 

Here is my PR for release 130.0-1.
Same as usual, I'll test this one before publishing.

Take care ! :wave:

### CODE REVIEW

**Comment by SpidFightFR** [comment]
image

Can confirm, it works !

**Comment by quincyf467** [comment]
Appreciate it. They just released 130.0-3 on Sep 7, 2024, 10:16 AM CDT.  Can update you update _rev=1 to _rev=3 please

**Comment by SpidFightFR** [comment]
> Appreciate it. They just released 130.0-3 on Sep 7, 2024, 10:16 AM CDT. Can update you update _rev=1 to _rev=3 please

good idea, please grant me 20 minutes (+-) while i run the required tests.

**Comment by SpidFightFR** [comment]
PR goes back to draft until everything is ready for prod.

**Comment by SpidFightFR** [comment]
image

Looks good to me.

**Comment by quincyf467** [comment]
Can concur.  Tested on x86_64-musl. Works fine. Thanks!

**Comment by index-0** [comment]
Thanks!

**Pull request merged**
