### PR TITLE
librewolf update to version 122.0-2.

### PR DESCRIPTION
**Pull request by SpidFightFR**
Hey there, it seems like the librewolf team has published a hotfix.

I'll be testing this one as well, you know the drill.

Have good day, lad ! :smile:

### CODE REVIEW

**Comment by SpidFightFR** [comment]
image

**Comment by SpidFightFR** [comment]
It's all good.

Also just in case, i forgot to bump the revision of the template, in order to not rely on the `-f` flag with `xbps`.
I mean... I could have worked otherwise too, but i prefer when it's simpler. :sweat_smile:

**Comment by index-0** [comment]
Thanks! Have a nice day too.

Don't worry about the _rev variable, I added it in case a rev bump from me is needed in the future, but I don't see such a scenario since this package is currently source only (because the build was too big for the GitHub actions runner and it ended up filling the docker container, but not anymore, so now it's possible that in the future a .xbps could be provided in the release section as a transparent build).

**Comment by MatiasConTilde** [comment]
how can I install librewolf from the releases section without having to compile it? can I add it as a repository to xbps?

**Comment by SpidFightFR** [comment]
> how can I install librewolf from the releases section without having to compile it? can I add it as a repository to xbps?

Afaik it's only the source code, not a binary...

@index-0 can't we do an automatic building task within github for the release tab ?

**Comment by index-0** [comment]
@SpidFightFR, did it yesterday, now the repository has transparent builds.

@MatiasConTilde, I just updated the README.md, hope that helps.

**Comment by SpidFightFR** [comment]
Average @index-0 W. :pray:

**Pull request merged**
