### PR TITLE
librewolf: update to version 120.0-2

### PR DESCRIPTION
**Pull request by SpidFightFR**
Hey ! :wave: 

A little PR as Draft, for librewolf 120.0-1.
If everything works out, it's going to be a normal PR.

Have a nice day !

### CODE REVIEW

**Comment by index-0** [comment]
Thanks! Have a great day!

**Comment by SpidFightFR** [comment]
image

Yup it's good! 

Have a nice day as well !

**Comment by SpidFightFR** [comment]
Needs testing :sweat_smile:

**Comment by SpidFightFR** [comment]
image

It works !

**Pull request merged**
